VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = 'ubuntu/xenial64'

    config.vm.provision "shell" do |s|
      ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
      s.inline = <<-SHELL
        echo #{ssh_pub_key} >> /home/ubuntu/.ssh/authorized_keys
        echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
      SHELL
    end

    config.ssh.insert_key = false

    config.vm.provision :shell, path: "requirements.sh"

    config.vm.provision :ansible do |ansible|
        ansible.groups = {
            "localhost" => ["default"],
        }
        ansible.playbook = 'playbook.yml'
        ansible.extra_vars = { ansible_ssh_user: 'root' }
        ansible.verbose = 'vv'
    end
end
