---
- name: Include variables suitable to our OS Family
  include_vars: "{{ ansible_os_family }}.yml"

- name: Include tasks suitable to our OS Family
  include: "{{ ansible_os_family }}.yml"

- name: Place base64 encoded driver
  copy:
    src: "{{ driver_file_name }}.base64"
    dest: "/usr/local/bin/{{ driver_file_name }}.base64"
  become: true

- name: Decode driver
  shell: "cat /usr/local/bin/{{ driver_file_name }}.base64 | base64 -d > /usr/local/bin/{{ driver_file_name }}"
  become: true

- name: set privileges
  file:
    path: "/usr/local/bin/{{ driver_file_name }}"
    mode: 0755
    owner: root
    group: root
  become: true

- name: run driver install script
  shell: "./{{ driver_file_name }} --keep --nox11;touch /usr/local/bin/dis-driv-inst.txt"
  args:
    chdir: /usr/local/bin/
    creates: /usr/local/bin/dis-driv-inst.txt
  become: true
  
- name: start upon boot
  systemd:
    name: dlm.service
    enabled: yes
    state: started
  become: true
  tags: usb
