---
- name: Fetch driverLinkDisplay
  get_url: 
    url: "{{ driver_download_url }}"
    dest: /usr/local/bin/displayLinkDriver.zip    
  become: true 
   
- name: unzip driver
  unarchive: 
    src: /usr/local/bin/displayLinkDriver.zip
    dest: /usr/local/bin/displayLinkDriver.run
  become: true

- name: set priviledges
  file: 
    src: /usr/local/bin/displayLinkDriver.run
    mode: 0755
    owner: root
    group: root
  become: true

- name: run driver
  command: ./usr/local/bin/displayLinkDriver.run
  become: true
