---
- name: Fetch driverLinkDisplay
  get_url:
    url: "{{ driver_download_url }}"
    dest: /usr/local/bin/displayLinkDriver.zip
  become: true

- name: unzip driver
  unarchive:
    src: /usr/local/bin/displayLinkDriver.zip
    dest: /usr/local/bin/
  become: true

- name: set priviledges
  file:
    path: "/usr/local/bin/displaylink-driver-{{ version }}.run"
    mode: 0755
    owner: root
    group: root
  become: true

- name: run driver install script
  shell: "./displaylink-driver-{{ version }}.run --keep --nox11"
  args:
    chdir: /usr/local/bin/
  become: true
  
- name: start upon boot
  systemd:
    name: dlm.service
    enabled: yes
    state: started
  become: true
